language: python
before_install: pip install -r requirements.txt
script: py.test
notifications:
  irc:
    channels:
      - "chat.freenode.org#titoufaitdestests"
    template:
      - "%{repository_name} (%{branch}:%{commit}) %{commit_message} : %{message}"
      - "Build details: %{build_url}"
    on_success: change
    on_failure: always
