language: python
sudo: false
before_install: pip install -r requirements.txt
script:
  - py.test
  - "cd doc/ && make html"
python:
  - "3.4"
  - "3.5"
notifications:
  irc:
    channels:
      - "chat.freenode.org#titoufaitdestests"
    template:
      - "%{repository_name} (%{branch}) %{message} by %{commit} %{commit_message} "
      - "%{build_url}"
    on_success: change
    on_failure: always
    use_notice: true
