language: python
before_install: pip install -r requirements.txt
script: py.test
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
notifications:
  irc:
    channels:
      - "chat.freenode.org#titoufaitdestests"
    template:
      - "%{repository_name} (%{branch}:%{commit}) %{commit_message} : %{message}"
      - "Build details: %{build_url}"
    on_success: change
    on_failure: always
